### ISSUE TITLE
plr_z.sh has not enough permision or file/directory created

### ISSUE THREAD

**Issue by DomoVlas** [Travis90x/Klipper-configuration#1]
Hi,

my problem is that the plr_z.sh can´t find these files because they are not present or created in my PI.

cp /home/lukaso1/printer_data/gcodes/.thumbs/${4}.png /home/lukaso1/printer_data/gcodes/.thumbs/plr.png
cp /home/lukaso1/printer_data/gcodes/.thumbs/${4}-32x32.png /home/lukaso1/printer_data/gcodes/.thumbs/plr-32x32.png
cp /home/lukaso1/printer_data/gcodes/.thumbs/${4}-400x400.png /home/lukaso1/printer_data/gcodes/.thumbs/plr-400x400.png

and also any gcode_macro from power-loss-recovery.cfg does not seem to use saved variables to create plr.gcode.

And this is in Klippy.LOG

shell_command: Command {POWER_LOSS_RESUME_Z} failed
Traceback (most recent call last):
  File "/home/lukaso1/klipper/klippy/extras/gcode_shell_command.py", line 53, in cmd_RUN_SHELL_COMMAND
    proc = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/lukaso1/printer_data/config/scripts/plr_z.sh'
Error running command {POWER_LOSS_RESUME_Z}

**Comment by Travis90x** [comment]
Reinstall Gcode Shell Command with Kiauh, update the script and let me know if issue persists.

Remember to set

[save_variables]
filename: ~/printer_data/config/save_variables.cfg

**Comment by DomoVlas** [comment]
Hi I am now getting no such file or directory.
![obrázok](https://github.com/Travis90x/Klipper-configuration/assets/155496807/38532d15-548d-42f5-a702-eb0d12acc78d)

This is in file i have from you:
![obrázok](https://github.com/Travis90x/Klipper-configuration/assets/155496807/d7e0d9fb-4360-440c-88e9-bf1cb10d2ef7)

**Comment by DomoVlas** [comment]
Do I need to have my RPI named "pi" ? or where is it trying to find the file plr.sh? i was following your manual where tu put it but some of these files alredy not exist or are in .cfg and not in .sh. Can you please revise your instructions on website?

**Comment by DomoVlas** [comment]
OK i got it working by changing this to path to the .sh file.
![obrázok](https://github.com/Travis90x/Klipper-configuration/assets/155496807/8b010424-21c2-462f-9ab2-a84e5a85aace)

But now I got PLR.gcode only like copy of the file printing before. PLR is attached.
[gcodes-202461-163110.zip](https://github.com/user-attachments/files/16054381/gcodes-202461-163110.zip)
